apiVersion: v1
kind: ConfigMap

metadata:
  name: mm-frontend-config
  namespace: mm-project
  labels:
    app: mm-frontend
    version: v1

data:
  API_ENDPOINT: "http://mm-api-service:3000"
  
  APP_TITLE: "Milestone 2"
  LOG_LEVEL: "info"
