apiVersion: v1
kind: Secret

metadata:
  name: mm-mongodb-secret
  namespace: mm-project
  labels:
    app: mm-database

type: Opaque

data:
  MONGO_INITDB_ROOT_USERNAME: cm9vdA==
  
  MONGO_INITDB_ROOT_PASSWORD: cm9vdHBhc3N3b3Jk
